// Generated by BUCKLESCRIPT VERSION 3.1.4, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Marker$MyProjectName = require("./Marker.bs.js");
var Fetcher$MyProjectName = require("./Fetcher.bs.js");
var Markers$MyProjectName = require("./Markers.bs.js");
var Geography$MyProjectName = require("./Geography.bs.js");
var Geographies$MyProjectName = require("./Geographies.bs.js");
var ComposableMap$MyProjectName = require("./ComposableMap.bs.js");
var ZoomableGroup$MyProjectName = require("./ZoomableGroup.bs.js");

var component = ReasonReact.statelessComponent("DojoMap");

function str(prim) {
  return prim;
}

var marker = {
  name: "Brussels",
  coordinates: /* array */[
    4.357888,
    50.833456
  ],
  markerOffset: -25
};

function make() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */(function () {
              return Fetcher$MyProjectName.fetchPost("https://immense-river-25513.herokuapp.com/add-location", "suancarloj");
            }),
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("div", {
                          style: {
                            margin: "0 auto",
                            maxWidth: "980px",
                            width: "100%"
                          }
                        }, ReasonReact.element(/* None */0, /* None */0, ComposableMap$MyProjectName.make(/* record */[/* scale */800], 1000, 1000, {
                                  height: "auto",
                                  margin: "0 auto",
                                  width: "100%"
                                }, /* array */[ReasonReact.element(/* None */0, /* None */0, ZoomableGroup$MyProjectName.make(/* array */[
                                            0,
                                            20
                                          ], /* array */[
                                            ReasonReact.element(/* None */0, /* None */0, Geographies$MyProjectName.make("/world-50m.json", (function (geographies, projection) {
                                                        return $$Array.mapi((function (i, geography) {
                                                                      return ReasonReact.element(/* Some */[String(i)], /* None */0, Geography$MyProjectName.make(geography, projection, /* record */[
                                                                                      /* default : record */[
                                                                                        /* fill */"#ECEFF1",
                                                                                        /* stroke */"#607D8B",
                                                                                        /* strokeWidth */0.75,
                                                                                        /* outline */"none"
                                                                                      ],
                                                                                      /* hover : record */[
                                                                                        /* fill */"#CFD8DC",
                                                                                        /* stroke */"#607D8B",
                                                                                        /* strokeWidth */0.75,
                                                                                        /* outline */"none"
                                                                                      ],
                                                                                      /* pressed : record */[
                                                                                        /* fill */"#FF5722",
                                                                                        /* stroke */"#607D8B",
                                                                                        /* strokeWidth */0.75,
                                                                                        /* outline */"none"
                                                                                      ]
                                                                                    ], /* array */[]));
                                                                    }), geographies);
                                                      }))),
                                            ReasonReact.element(/* None */0, /* None */0, Markers$MyProjectName.make(/* array */[ReasonReact.element(/* None */0, /* None */0, Marker$MyProjectName.make(marker, /* record */[
                                                                /* default */{
                                                                  fill: "#FF5722"
                                                                },
                                                                /* hover */{
                                                                  fill: "#FFFFFF"
                                                                },
                                                                /* pressed */{
                                                                  fill: "#FF5722"
                                                                }
                                                              ], /* array */[
                                                                React.createElement("circle", {
                                                                      style: {
                                                                        opacity: "0.9",
                                                                        stroke: "#FF5722",
                                                                        strokeWidth: "3"
                                                                      },
                                                                      cx: "0",
                                                                      cy: "0",
                                                                      r: "10"
                                                                    }),
                                                                React.createElement("text", {
                                                                      style: {
                                                                        fontFamily: "Roboto, sans-serif",
                                                                        fill: "#607D8B"
                                                                      },
                                                                      textAnchor: "middle",
                                                                      y: "-25"
                                                                    }, "Brussels")
                                                              ]))]))
                                          ]))])));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

exports.component = component;
exports.str = str;
exports.marker = marker;
exports.make = make;
/* component Not a pure module */
